---
title: "Act1"
author: "Jojo"
date: "Wednesday, April 15, 2015"
output: html_document
---
```{r}
setwd("C:\\Users\\Minerva\\Dropbox\\Desk2015\\Rwork\\Rprog\\Reproducible Res\\Assgn1")
act=read.csv("activity.csv")
attach(act)
head(act)

summary(act)

```

Mean total number of steps
```{r}
TotalSteps= aggregate(steps ~ date, data = act, sum,na.rm=TRUE)

hist(TotalSteps$steps, main = "Total steps by day", xlab = "day", col = "red")

mean(TotalSteps$steps)

median(TotalSteps$steps)


```

Average daily pattern

```{r}
cact <- tapply(act$steps, act$interval, mean, na.rm = TRUE)

plot(row.names(cact), cact, type = "l", xlab = "5-min interval", 
    ylab = "Average across all Days", main = "Average number of steps taken", 
    col = "red")

maxint=which.max(cact)
names(maxint)


```

Missing values

```{r}
actNa=sum(is.na(act))

AverageStep <- aggregate(steps ~ interval, data = act, FUN = mean)
fillNA <- numeric()

for (i in 1:nrow(act)) {
    obs <- act[i, ]
    if (is.na(obs$steps)) {
        steps <- subset(AverageStep, interval == obs$interval)$steps
    } else {
        steps <- obs$steps
    }
    fillNA <- c(fillNA, steps)
}

newact=act

newact$steps=fillNA

Total2 <- aggregate(steps ~ date, data = newact, sum, na.rm = TRUE)

hist(Total2$steps, main = "Total steps by day", xlab = "day", col = "red")

mean(Total2$steps)
median(Total2$steps)


```

Weekdays vs weekends

```{r}
daytype <- function(date) {
    if (weekdays(as.Date(date)) %in% c("Saturday", "Sunday")) {
        "weekend"
    } else {
        "weekday"
    }
}
act$daytype <- as.factor(sapply(act$date, daytype))

par(mfrow = c(2, 1))
for (type in c("weekend", "weekday")) {
    steps.type <- aggregate(steps ~ interval, data = act, subset = act$daytype == 
        type, FUN = mean)
    plot(steps.type, type = "l", main = type)
}


```


